# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# ----
variables:
  system.debug: true
trigger:
- master
stages:
- stage: BuildStage
  displayName: BuildStage
  jobs:  
  - job: delayJob
    pool: server
    displayName: delayJob
    timeoutInMinutes: 1
    steps:
    - task: Delay@1
      timeoutInMinutes: 2
      inputs:
        delayForMinutes: '3'
  - job: job2    
    displayName: job2
    dependsOn: delayJob
    steps:
      - script: echo hellowrold!
- stage: QAStage
  displayName: QAStage
  dependsOn: BuildStage
  jobs:  
  - job: jobinqa    
    displayName: jobinqa
    steps:
      - script: echo hellowrold-QA!
