# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# ----

trigger:
- master
stages:
- stage: Build
  displayName: BuildStage
  jobs:  
  - job: BuildJob
    displayName: BuildJob
    steps:
    - script: | 
        echo Hello, world !! 
        echo Replace me with your build steps !!
      displayName: 'Build task'
    - powershell: Write-Host "Run unit tests for your application..."        
      displayName: 'Unit Testing'
    - task: PublishPipelineArtifact@0
      displayName: Publish Artifacts
      inputs:
        artifactName: drop
        targetPath: '$(Build.SourcesDirectory)'
- stage: DeployStage
  displayName: DeployStage
  jobs:
  - deployment: DeployJob
    displayName: DeployJob
    pool:
      vmImage: Ubuntu-16.04
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello


